### ISSUE TITLE
shoutbox-thin comsuming nearly all memory/ram

### ISSUE THREAD

**Issue by leitmedium** [bk-one/shoutbox#15]
PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND  
11502 rails     20   0 9502m 7.3g 1600 R   95 93.7   2694:16 thin

**Comment by abuiles** [comment]
@damokles in the pusher work I update the version of thin and sinatra, let's see how the new one behaves.
